### PR TITLE
Use cylinders in place of lines in order to get a line width working on all platforms

### PR DESCRIPTION
**Pull request by Juleffel**
Add three arguments:
`linkVal` , `linkDefaultWidth` , `linkResolution`
Example in example/lineWidth/

### CODE REVIEW

**Comment by AmbroiseCouissin** [comment]
Hi @Juleffel,

Isn't the support for MeshLine better for this?:
https://github.com/vasturiano/3d-force-graph/issues/16

Cheers

**Comment by Juleffel** [comment]
Well, I actually already tried that, in fact. You can use the code at commit https://github.com/Juleffel/aframe-forcegraph-component/commit/9d82fb8bee9f51476849f78b2cf0e16b536c92d6
Unfortunately, I have an error I don't understand, using them (something about `t` being undefined in three.js).
It may have been an error of modules compatibility ; but I wasn't able to solve it. I then decided to try using cylinders with low number of triangles instead, one advantage being not using more libraries.
If you want to give it a try, you can use my code, it's inspired from the spinner demo from their project ( https://www.clicktorelease.com/code/THREE.MeshLine/demo/spinner.html ).

**Comment by Juleffel** [comment]
In fact now that the imports are more properly done (specially for three, I think), it works well. I sent another PR with the MeshLine implementation https://github.com/vasturiano/three-forcegraph/pull/3 .
I'm not sure if we should choose a default implementation or give the user a choice.

**Comment by vasturiano** [comment]
Thanks for this PR @Juleffel!

I've refactored it a little to support both cylinder and line geometries (if linkWidth = 0), as using cylinders alters the link cosmetics slightly, and line may be preferable in some cases.

**Pull request merged**
